### ISSUE TITLE
1.1.0 Road Map

### ISSUE THREAD

**Issue by WeihanLi** [WeihanLi/WeihanLi.Common#82]
- [x] Built-In IoC
- [x] Built-In AOP
- [x] Built-In Repository
- [x] Built-In Logging
- [x] Built-In TOTP implement
- [x] Built-In EventBus
- [x] Built-In PipelineBuilder
- [x] #120 
- [x] #188 
- [ ] #121
- [ ] #294 
- [ ] And More ...
